[project]
name = "hoshinobot-ellye"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiocache==0.12.3",
    "aiocqhttp==1.4.4",
    "aiofiles==24.1.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiosignal==1.4.0",
    "annotated-types==0.7.0",
    "anyio==4.10.0",
    "apscheduler==3.11.0",
    "attrs==25.3.0",
    "beautifulsoup4==4.13.4",
    "bleach==6.2.0",
    "blinker==1.9.0",
    "certifi==2025.8.3",
    "cffi==1.17.1",
    "charset-normalizer==3.4.3",
    "click==8.2.1",
    "colorama==0.4.6",
    "contourpy==1.3.3",
    "cssselect==1.3.0",
    "cssutils==2.11.1",
    "cycler==0.12.1",
    "dataframe-image==0.2.7",
    "defusedxml==0.7.1",
    "fastjsonschema==2.21.2",
    "filetype==1.2.0",
    "flask==3.1.2",
    "fonttools==4.59.1",
    "frozenlist==1.7.0",
    "fuzzywuzzy==0.18.0",
    "greenlet==3.2.4",
    "h11==0.16.0",
    "h2==4.2.0",
    "hpack==4.1.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "hypercorn==0.17.3",
    "hyperframe==6.1.0",
    "idna==3.10",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "jsonschema==4.25.1",
    "jsonschema-specifications==2025.4.1",
    "jupyter-client==8.6.3",
    "jupyter-core==5.8.1",
    "jupyterlab-pygments==0.3.0",
    "kiwisolver==1.4.9",
    "lxml==6.0.1",
    "markupsafe==3.0.2",
    "matplotlib==3.10.5",
    "mistune==3.1.3",
    "more-itertools==10.7.0",
    "mpmath==1.3.0",
    "msgpack==1.1.1",
    "multidict==6.6.4",
    "naked==0.1.32",
    "nbclient==0.10.2",
    "nbconvert==7.16.6",
    "nbformat==5.10.4",
    "nonebot==1.9.1",
    "numpy==2.2.6",
    "opencv-python==4.12.0.88",
    "outcome==1.3.0.post0",
    "packaging==25.0",
    "pandas==2.3.2",
    "pandocfilters==1.5.1",
    "peewee==3.18.2",
    "pillow==11.3.0",
    "platformdirs==4.3.8",
    "playwright==1.54.0",
    "priority==2.0.0",
    "propcache==0.3.2",
    "pycparser==2.22",
    "pycryptodome==3.23.0",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pyee==13.0.0",
    "pyenchant==3.2.2",
    "pygments==2.19.2",
    "pygtrie==2.5.0",
    "pyparsing==3.2.3",
    "pysocks==1.7.1",
    "python-dateutil==2.9.0.post0",
    "python-levenshtein>=0.27.1",
    "pytz==2025.2",
    # "pywin32==311", # 在 Linux 下不支持，仅适用于 Windows
    "pyyaml==6.0.2",
    "pyzmq==27.0.2",
    "quart==0.20.0",
    "referencing==0.36.2",
    "requests==2.32.5",
    "rpds-py==0.27.0",
    "selenium==4.35.0",
    "shellescape==3.8.1",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sortedcontainers==2.4.0",
    "soupsieve==2.7",
    "sqlitedict==2.1.0",
    "sympy==1.14.0",
    "tinycss2==1.4.0",
    "tornado==6.5.2",
    "traitlets==5.14.3",
    "trio==0.30.0",
    "trio-websocket==0.12.2",
    "typing-extensions==4.14.1",
    "typing-inspection==0.4.1",
    "tzdata==2025.2",
    "tzlocal==5.3.1",
    "ujson==5.11.0",
    "urllib3==2.5.0",
    "webencodings==0.5.1",
    "websocket-client==1.8.0",
    "werkzeug==3.1.3",
    # "wmi==1.5.1", # 在 Linux 下不支持，仅适用于 Windows
    "wsproto==1.2.0",
    "yarl==1.20.1",
    "zhconv==1.4.3",
]

[[tool.uv.index]] 
url = "https://mirrors.cloud.tencent.com/pypi/simple"
default = true

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = false

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = false
